version: "3"

services: 
  postgres:
    image: postgres:12.1-alpine
    environment: 
      - POSTGRES_USER=teamseven
      - POSTGRES_PASSWORD=teamseven
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - postgresql:/var/lib/postgresql
    networks: 
      - atnet

  sonarqube:
    image: sonarqube:8.9.0-community
    environment: 
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/teamseven
      - SONAR_JDBC_USERNAME=teamseven
      - SONAR_JDBC_PASSWORD=teamseven
    ports:
      - 9000:9000
    networks: 
      - atnet
    depends_on: 
      - postgres
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_data:/opt/sonarqube/data

  jenkins:
    image: jenkins/jenkins:lts
    ports: 
      - 8080:8080
      - 5000:5000
    networks:
      - atnet
    volumes:
      - jenkins_home:/var/jenkins_home

  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    networks:
      - atnet
    volumes:
      - nexus-data:/nexus-data

networks:
  atnet:

volumes:
  postgresql_data:
  postgresql:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_data:
  jenkins_home:
  nexus-data:
