Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box_check_update = true
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 8080, host: 8090
  config.vm.network "forwarded_port", guest: 50000, host: 50000
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    vb.name = "ATDockerLT"
    vb.cpus = 2
    vb.memory = "8096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo sysctl -w vm.max_map_count=262144
    curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > "/dev/null"
    apt update && apt upgrade -y
    apt install docker-ce docker-ce-cli containerd.io docker-compose -y
    mkdir /ATDockerLT
    cd /ATDockerLT
    git clone https://github.com/zkpain/ATDockerLT.git
    sudo sysctl -w vm.max_map_count=262144
    cd /ATDockerLT/ATDockerLT/docker-compose
    sudo docker-compose up -d
    sudo docker container logs docker-compose_sonarqube_1
    sudo docker container ls
  SHELL
end